version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: settlement-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: settlement_db
      MYSQL_USER: stmt
      MYSQL_PASSWORD: stmt12
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: